### ISSUE TITLE
logsumexp has moved to scipy.special in newer versions of scipy

### ISSUE THREAD

**Issue by fig-foodisgood** [tyjo/luminate#1]
http://pageperso.lif.univ-mrs.fr/~francois.denis/IAAM1/scipy-html-1.0.0/generated/scipy.special.logsumexp.html.

Get a few errors when running examples because import location has to be updated.

**Comment by tyjo** [comment]
This should be fixed now, thanks!

**Comment by apascualgarcia** [comment]
Dear Tyler,

The problem still persists, after installing requirements in a conda environment, running `./run-examples.sh` leads to the error:

`ImportError: cannot import name 'logsumexp' from 'scipy.misc' `

The issue can be solved installing `scipy==1.2.1` instead, for some reason in the version suggested in `requirements.txt` the function seems to be in another module. With the version 1.2.1 the code works.

**Comment by tyjo** [comment]
Thanks for bringing this to my attention.

The import statement in `main.py`did not get updated with the rest of the code. I believe this should be resolved now, but let me know if you run into any trouble.

**Comment by apascualgarcia** [comment]
I confirm I can run it now with `scipy-1.5.3`, thanks for the quick response.
